name: Build iOS IPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (No Codesign)
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          mkdir -p build/ios/Payload
          mv build/ios/iphoneos/Runner.app build/ios/Payload/
          cd build/ios
          zip -qr app.ipa Payload/

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stream_vault_ios
          path: build/ios/app.ipa
